import React, { useState, useEffect } from 'react'
import "./registrationForm.css"

const RegistrationForm = () => {

   const [input, setInput] = useState("")

   const handleChange = e => {
      setInput(e.target.value);
      console.log(input)
   }

   const handleSubmit = e => {
      console.log("form submitted successfully")
   }


   return(
      <div className="registrationForm">
         <form onSubmit={handleSubmit}>
            <label htmlFor="sname">Random Screen Name</label>
            <input
               type="text"
               id="sname"
               name="sname"
               placeholder="Random Screen Name"
               // random screen name generated by hyperlink label
            />

            <label htmlFor="fname">First Name</label>
            <input
               type="text"
               id="fname"
               name="firstName"
               placeholder="First Name"
               onChange={handleChange}
            />

            <label htmlFor="lname">Last Name</label>
            <input
               type="text"
               id="lname"
               name="lastName"
               placeholder="Last Name"
               onChange={handleChange}
            />

            <label htmlFor="street">Street Address</label>
            <input
               type="text"
               id="street"
               name="street"
               placeholder="Street Adress"
               onChange={handleChange}
            />

            <label htmlFor="city">City</label>
            <input
               type="text"
               id="city"
               name="city"
               placeholder="City"
               onChange={handleChange}
            />

            <label htmlFor="state">State</label>
            <input
               type="text"
               id="state"
               name="state"
               placeholder="State"
               onChange={handleChange}
            />

            <label htmlFor="zip">Zipcode</label>
            <input
               type="number"
               id="zip"
               name="zip"
               placeholder="Zip Code"
               onChange={handleChange}
            />

            <label htmlFor="password">Password</label>
            <input
               type="password"
               id="password"
               name="password"
               placeholder="Password"
               onChange={handleChange}
            />

            <label htmlFor="children">Number of Children</label>
            <input
               type="number"
               id="children"
               name="children"
               placeholder="Number Of Children"
               onChange={handleChange}
            />

            <label htmlFor="ecname">Emergency Contact Name</label>
            <input
               type="text"
               id="ecname"
               name="ecname"
               placeholder="Emergency Contact Name"
               onChange={handleChange}
            />

            <label htmlFor="ecnumber">Emergency Contact Number</label>
            <input
               type="number"
               id="ecnumber"
               name="ecnumber"
               placeholder="Emergency Contact Phone Number"
               onChange={handleChange}
            />

            <input type="submit"></input>
         </form>
      </div>
   )
}

export default RegistrationForm